# Generated by Django 4.2 on 2023-04-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('input_registers_number', models.PositiveIntegerField(default=0)),
                ('holding_registers_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.structure')),
            ],
        ),
        migrations.CreateModel(
            name='StructureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('map', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.map')),
                ('sub_structure', models.ManyToManyField(to='map.substructure')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='structure',
            field=models.ManyToManyField(to='map.substructure'),
        ),
    ]
