# Generated by Django 4.2 on 2023-04-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='structure',
            new_name='sub_structure',
        ),
    ]
