# Generated by Django 4.2 on 2023-04-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_structure_map_sub_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bytes', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('I', 'input'), ('H', 'holding')], max_length=1)),
                ('data_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.datatype')),
            ],
        ),
    ]
