# Generated by Django 4.2 on 2023-05-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_datatype_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='structure',
            name='holding_registers_number',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='input_registers_number',
        ),
    ]
