# Generated by Django 4.2 on 2023-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_register_options_alter_structure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='structure',
            name='registers',
            field=models.ManyToManyField(related_query_name='structures', to='map.register'),
        ),
    ]
