# Generated by Django 4.2 on 2023-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_register_options_alter_structure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='registers',
            field=models.ManyToManyField(to='map.register'),
        ),
    ]
