# Generated by Django 4.2 on 2023-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_structure_registers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={},
        ),
    ]
