# Generated by Django 4.2 on 2023-05-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_structure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
    ]
